# Generated by Django 3.1.7 on 2021-04-06 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('address', models.TextField(blank=True, max_length=100)),
                ('full_name', models.TextField(blank=True, max_length=100)),
                ('tel', models.TextField(blank=True, max_length=100)),
                ('country', models.TextField(blank=True, max_length=100)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('you_are', models.TextField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
