# Generated by Django 3.1.7 on 2021-04-06 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.TextField(choices=[('Motorbike', 'Motorbike'), ('Scooter', 'Motorbike'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('MPV/Minivan', 'MPV/Minivan'), ('SUV', 'SUV'), ('CUV/Crossover', 'CUV/Crossover'), ('Pickup', 'Pickup'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Station Wagon', 'Station Wagon'), ('Van', 'Van'), ('Three-Wheeler', 'Three-Wheeler'), ('Lorry', 'Lorry'), ('Bus', 'Bus')], max_length=100)),
                ('brand', models.TextField(max_length=100)),
                ('model', models.TextField(max_length=50)),
                ('category', models.TextField(choices=[('New', 'New'), ('Used', 'Used')], max_length=100)),
                ('year', models.IntegerField()),
                ('fuel', models.TextField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric(ECV)', 'Electric(ECV)'), ('Hybrid(HEV)', 'Hybrid(HEV)'), ('LPG Autogas', 'LPG Autogas'), ('Biofuel', 'Biofuel')], max_length=100)),
                ('transmission', models.TextField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic'), ('CVT', 'CVT')], max_length=100)),
                ('milage', models.IntegerField()),
                ('engine', models.TextField(max_length=50)),
                ('image1', models.ImageField(upload_to='upload_to=images/%Y/%m/%d/')),
                ('image2', models.ImageField(upload_to='upload_to=images/%Y/%m/%d/')),
                ('image3', models.ImageField(upload_to='upload_to=images/%Y/%m/%d/')),
                ('image4', models.ImageField(upload_to='upload_to=images/%Y/%m/%d/')),
                ('image5', models.ImageField(upload_to='upload_to=images/%Y/%m/%d/')),
                ('description', models.CharField(max_length=250)),
                ('condition', models.TextField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fairly Good', 'Fairly Good'), ('Fairly Poor', 'Fairly Poor'), ('Poor', 'Poor')], max_length=100)),
                ('price', models.IntegerField()),
                ('tel', models.TextField(max_length=10)),
                ('city', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('vote_total', models.IntegerField(default=1)),
                ('location', osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon')),
                ('location_lat', osm_field.fields.LatitudeField(validators=[osm_field.validators.validate_latitude])),
                ('location_lon', osm_field.fields.LongitudeField(validators=[osm_field.validators.validate_longitude])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
