# Generated by Django 3.1.7 on 2021-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='fuel',
            field=models.TextField(choices=[('Gas', 'Petrol'), ('Diesel', 'Diesel'), ('Electric(ECV)', 'Electric(ECV)'), ('Hybrid(HEV)', 'Hybrid(HEV)'), ('LPG Autogas', 'LPG Autogas'), ('Biofuel', 'Biofuel')], max_length=100),
        ),
    ]
