# Generated by Django 3.2.15 on 2022-08-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_auto_20210511_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishing',
            old_name='engine',
            new_name='procesor',
        ),
        migrations.RenameField(
            model_name='publishing',
            old_name='milage',
            new_name='ram',
        ),
        migrations.RemoveField(
            model_name='publishing',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='publishing',
            name='transmission',
        ),
        migrations.AddField(
            model_name='publishing',
            name='storage',
            field=models.TextField(choices=[('80GB', '80GB'), ('156GB', '156GB'), ('256GB', '256GB'), ('512GB', '512GB')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publishing',
            name='type',
            field=models.TextField(choices=[('Apple', 'Apple'), ('HP', 'HP'), ('Acer', 'Acer'), ('Asus', 'Hatchback'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Microsoft', 'Microsoft'), ('NotePad', 'NotePad'), ('Toshiba', 'Toshiba'), ('Google', 'Google'), ('Samsung', 'Samsung')], max_length=100),
        ),
    ]
