# Generated by Django 3.2.15 on 2022-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_auto_20220822_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='brand',
            field=models.TextField(choices=[('Apple', 'Apple'), ('HP', 'HP'), ('Acer', 'Acer'), ('Asus', 'Hatchback'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Microsoft', 'Microsoft'), ('NotePad', 'NotePad'), ('Toshiba', 'Toshiba'), ('Google', 'Google'), ('Samsung', 'Samsung')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image1',
            field=models.ImageField(null=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image2',
            field=models.ImageField(null=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image3',
            field=models.ImageField(null=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image4',
            field=models.ImageField(null=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image5',
            field=models.ImageField(null=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='type',
            field=models.TextField(max_length=100),
        ),
    ]
