# Generated by Django 3.2.15 on 2022-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0004_auto_20220822_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='publishing',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='publishing',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='publishing',
            name='image5',
        ),
        migrations.AlterField(
            model_name='publishing',
            name='category',
            field=models.TextField(choices=[('Used', 'Used'), ('New', 'New')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='storage',
            field=models.TextField(choices=[('0GB', '0GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1000GB', '1000GB'), ('2000GB', '2000GB')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='type',
            field=models.TextField(choices=[('Ultrabook', 'Ultrabook'), ('Thinkpad', 'Thinkpad'), ('Gaming', 'Gaming'), ('2 in 1', '2 in 1')], max_length=100),
        ),
    ]
